[package]
name = "activitypub_federation"
version = "0.2.3"
edition = "2021"
description = "High-level Activitypub framework"
license = "AGPL-3.0"
repository = "https://github.com/LemmyNet/activitypub-federation-rust"
documentation = "https://docs.rs/activitypub_federation/"

[workspace]
members = ["derive"]

[dependencies]
activitypub_federation_derive = { version = "0.2.0", path = "derive" }
chrono = { version = "0.4.22", features = ["clock"], default-features = false }
serde = { version = "1.0.145", features = ["derive"] }
async-trait = "0.1.57"
url = { version = "2.3.1", features = ["serde"] }
serde_json = { version = "1.0.85", features = ["preserve_order"] }
anyhow = "1.0.65"
reqwest = { version = "0.11.12", features = ["json"] }
reqwest-middleware = "0.1.6"
tracing = "0.1.36"
base64 = "0.13.0"
openssl = "0.10.60"
once_cell = "1.15.0"
http = "0.2.8"
sha2 = "0.10.6"
actix-web = { version = "4.2.1", default-features = false }
http-signature-normalization-actix = { version = "0.6.1", default-features = false, features = ["server", "sha-2"] }
http-signature-normalization-reqwest = { version = "0.6.0", default-features = false, features = ["sha-2", "middleware"] }
background-jobs = "0.13.0"
thiserror = "1.0.37"
derive_builder = "0.11.2"
itertools = "0.10.5"
dyn-clone = "1.0.9"

[dev-dependencies]
activitystreams-kinds = "0.2.1"
rand = "0.8.5"
actix-rt = "2.7.0"
tokio = "1.24.2"
env_logger = { version = "0.9.1", default-features = false }
